import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  //Login and Signup Form Styles
  formWrapper: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "white",
    padding: 20,
  },
  logo: {
    width: 300,
    height: 150,
    marginBottom: 20,
    resizeMode: "contain",
  },
  form: {
    flexDirection: "column",
    width: "100%",
    maxWidth: 400,
    alignSelf: "center",
    paddingHorizontal: 20,
  },
  heading: {
    textAlign: "center",
    fontSize: 28,
    marginBottom: 20,
    color: "#333",
  },
  inputGroup: {
    marginBottom: 20,
    position: "relative",
  },
  inputLabel: {
    marginBottom: 5,
    fontSize: 16,
    color: "#333",
  },
  inputTextBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "transparent",
    borderBottomWidth: 2,
    borderBottomColor: "#01c289",
    padding: 10,
  },
  icon: {
    marginRight: 10,
    color: "#333",
  },
  textInput: {
    flex: 1,
    fontSize: 16,
    padding: 10,
  },
  switchText: {
    marginTop: 20,
    textAlign: "center",
    color: "#333",
    fontSize: 16,
    marginBottom: 20,
    padding: 10,
    borderRadius: 8,
    backgroundColor: "transparent",
  },
  button: {
    backgroundColor: "#01c289",
    padding: 15,
    borderRadius: 8,
    marginTop: 20,
  },
  buttonText: {
    color: "white",
    fontWeight: "bold",
    textAlign: "center",
    fontSize: 16,
  },
  passwordToggle: {
    position: "absolute",
    right: 10,
    padding: 5,
  },
  //Home Styles
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
  },
  logo: {
    width: "100%",
    height: 120,
    resizeMode: "contain",
    alignSelf: "center",
    marginTop: -10,
  },
  line: {
    height: 2,
    backgroundColor: "#01c289",
    marginVertical: 5,
  },
  greetingBox: {
    backgroundColor: "#01c289",
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 8,
    marginTop: 10,
    marginBottom: 10,
  },
  greetingText: {
    fontSize: 18,
    color: "#333",
    textAlign: "center",
    flexShrink: 1,
  },
  carouselContainer: {
    width: "100%",
    height: 200,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
    marginBottom: 10,
  },
  carouselImage: {
    borderRadius: 8,
    width: 350,
    height: 200,
    resizeMode: "cover",
    borderColor: "#333",
    borderWidth: 3,
  },
  eventContainer: {
    backgroundColor: "#01c289",
    borderRadius: 8,
    padding: 16,
    marginVertical: 10,
    borderColor: "#333",
    borderWidth: 3,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  eventLogo: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginBottom: 10,
  },
  eventTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    marginTop: 5,
    marginBottom: 5,
  },
  eventImage: {
    width: "100%",
    height: 200,
    borderRadius: 8,
    marginVertical: 10,
    resizeMode: "cover",
  },
  eventDescription: {
    fontSize: 16,
    color: "#333",
    textAlign: "center",
    marginTop: 15,
    marginBottom: 15,
  },
  eventFooter: {
    fontSize: 14,
    color: "#555",
    textAlign: "center",
  },
  navContainer: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    padding: 10,
    borderTopWidth: 1,
    borderTopColor: "#ddd",
    backgroundColor: "#fff",
  },
  iconWrapper: {
    padding: 10,
  },
  discoverTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#333",
    textAlign: "center",
    marginVertical: 10,
  },
  addEventButton: {
    backgroundColor: "#01c289",
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 8,
    alignSelf: "center",
    marginVertical: 10,
  },
  addEventButtonText: {
    fontSize: 16,
    color: "#fff",
    fontWeight: "bold",
    textAlign: "center",
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalContent: {
    width: "90%",
    backgroundColor: "#fff",
    borderColor: "#01c289",
    borderWidth: 3,
    borderRadius: 10,
    padding: 20,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 20,
    marginTop: 20,
    textAlign: "center",
    color: "#333",
  },
  input: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 8,
    padding: 10,
    marginBottom: 15,
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
  },
  buttonPickLogo: {
    backgroundColor: "#01c289",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    marginBottom: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonPickLogoText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
  },
  noEventsText: {
    fontSize: 16,
    color: "#d3d3d3",
    textAlign: "center",
    marginTop: 180,
  },
  noLogoText: {
    fontSize: 16,
    color: "#444",
    textAlign: "center",
    marginBottom: 20,
  },
  discoverCard: {
    backgroundColor: "#f9f9f9",
    borderRadius: 12,
    padding: 20,
    marginVertical: 15,
    borderColor: "#01c289",
    borderWidth: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  discoverEventLogoContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
  },
  discoverEventLogo: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 12,
    backgroundColor: "#f0f0f0",
  },
  discoverEventOrg: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333",
    flexWrap: "wrap",
  },

  discoverEventTitle: {
    fontWeight: "bold",
    fontSize: 16,
  },

  discoverEventDescription: {
    fontSize: 16,
    color: "#555",
    marginTop: 15,
    marginBottom: 15,
    lineHeight: 24,
  },
  discoverEventDetailsContainer: {
    marginTop: 20,
  },
  eventDetailRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  eventDetailText: {
    fontSize: 14,
    color: "#666",
    marginLeft: 10,
  },
  signupButton: {
    backgroundColor: "#01c289",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 25,
    alignSelf: "center",
    marginTop: 10,
  },
  signupButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  activityCard: {
    backgroundColor: "#ffffff",
    borderRadius: 10,
    padding: 15,
    marginTop: 15,
    marginBottom: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  activityName: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#01c289",
    marginBottom: 5,
  },
  activityStatus: {
    fontSize: 16,
    color: "#555",
  },
  organizationDetails: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },
  organizationLogo: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginRight: 10,
  },
  organizationName: {
    fontSize: 18,
    fontWeight: "600",
  },
  modalDescription: {
    fontSize: 16,
    marginBottom: 20,
    color: "#555",
  },
  modalDetails: {
    marginVertical: 10,
  },
  modalDetailText: {
    fontSize: 16,
    marginVertical: 5,
    color: "#333",
  },

  profileImageContainer: {
    alignItems: "center",
    marginVertical: 20,
  },
  profileImage: {
    width: 100,
    height: 100,
    borderRadius: 50,
    marginTop: 60,
  },
  profileName: {
    fontSize: 18,
    fontWeight: "600",
    textAlign: "center",
    marginVertical: 5,
  },
  profileUsername: {
    fontSize: 16,
    color: "#555",
    textAlign: "center",
    marginVertical: 5,
  },
  profileBio: {
    fontSize: 14,
    color: "#777",
    textAlign: "center",
    marginVertical: 5,
  },
  profileEmail: {
    fontSize: 14,
    color: "#555",
    textAlign: "center",
    marginVertical: 5,
  },
  editButton: {
    backgroundColor: "#4CAF50",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
    marginVertical: 10,
    alignSelf: "center",
  },
  logoutButton: {
    backgroundColor: "#f44336",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
    marginVertical: 10,
    alignSelf: "center",
  },
  adminButtonsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
  },
  acceptButton: {
    backgroundColor: "#01c289",
    padding: 10,
    borderRadius: 5,
  },
  rejectButton: {
    backgroundColor: "#d9534f",
    padding: 10,
    borderRadius: 5,
  },
  acceptButtonText: {
    color: "#fff",
    fontWeight: "bold",
  },
  rejectButtonText: {
    color: "#fff",
    fontWeight: "bold",
  },
  statusText: {
    fontSize: 14,
    fontStyle: "italic",
    color: "#555",
  },
});

export default styles;
